services:
  metabase-db:
    container_name: metabase-db
    image: postgres:17.2
    restart: always  
    volumes:
      - "./data/metabase/pgdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=metabase
      - POSTGRES_USER=metabase
      - POSTGRES_PASSWORD=secret
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metabase -d metabase"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - metabase

  metabase-app:
    container_name: metabase-app
    image: metabase/metabase:latest
    platform: linux/amd64
    restart: always 
    volumes:
      - "./data/metabase/metabase-data:/metabase-data"
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=secret
      - MB_DB_HOST=metabase-db
    networks:
      - metabase

networks:
  metabase:
    driver: bridge