name: Build and Release Docker Image

on:
  push:
    tags: 'v*' # Triggers on versioned tags
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t metabase:latest .

      - name: Save Docker image to tar file
        run: |
          docker save metabase:latest -o metabase.tar

      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Docker image to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./metabase.tar
          asset_name: metabase.tar
          asset_content_type: application/x-tar
